### ISSUE TITLE
chapter 4 4.2 microprocessors

### ISSUE THREAD

**Issue by roshstar1999** [aradhana-arts/final_year_project_latex#10]
Page 13
1.first line
"Micro-processors acts" <==>"The Microprocessor acts"

2.line 4:
"micro-processor"<==>microprocessor

3. 2nd para 2nd line
opencv's<==> "OpenCV's"

4. 2nd para 3rd line 
harrcascade<==>"Haar Cascades"

5.5th line 2nd para
opencv<==>OpenCV

6.3rd para 1st line:
"Above process provides"<=>"The above process provides"

7.2nd last para in 4.2 2nd last line :
" calculate, panning and tilting angles, depth of
the listener from each speaker."<==> " calculate the panning, tilting angles, and depth of
the listener from each speaker."

###############see im not sure there is something called  panning angle ,so i made it panning, just cross check on google once
8.

**Comment by aradhana-arts** [comment]
In cinematography and photography panning means swiveling a still or video camera horizontally from a fixed position.This motion is similar to the motion of a person when they turn their head on their neck from left to right.

**Comment by aradhana-arts** [comment]
resolved
