### ISSUE TITLE
4.3 mechanical unit

### ISSUE THREAD

**Issue by roshstar1999** [aradhana-arts/final_year_project_latex#11]
1."As discussed in methodology, as the speakers propagates sound in oval"
As discussed in the methodology, the speakers propagate sound in elliptical shape

2. Hence shape we need to align<==> Hence  we need to align
3. 2nd para:
"Mechanical units assembles with, two servo motors
for each speaker (channel) one for panning and second
for tilting
"
<==>
The mechanical unit is consisting of two servo motors
for each speaker (channel), one for panning and the second
for tilting,

**Comment by aradhana-arts** [comment]
resolved
