### ISSUE TITLE
4.4 apu

### ISSUE THREAD

**Issue by roshstar1999** [aradhana-arts/final_year_project_latex#12]
1.3rd para 2nd line
two two-channel digital<==>  two 2-channel digital

2.  in 4.4.2 2nd line
micro-controllers= microcontrollers

3. in 4.4.2 2nd para last line
micro-controller=microcontroller

4.4.4.2 last line
Digital POT<==> digital pot

4.5 1st line:
 four channeled<=>channelled

**Comment by aradhana-arts** [comment]
resolved
