### ISSUE TITLE
few corrections in ABSTRACT

### ISSUE THREAD

**Issue by roshstar1999** [aradhana-arts/final_year_project_latex#5]
1) in ABSTRACT LINE 4:

 where I usually seat."
          to be replaced by:
"where I usually sit"

2) in ABSTRACT LINE 8:
 change my seating position
         TO BE REPLACED BY 
 "change my seat position"        OR  "change my sitting position"

3)also a suggestion to not use "I" in the paper, instead we could use person A or something like that.

**Comment by aradhana-arts** [comment]
All suggested changes have been resolved
