### ISSUE TITLE
ABSTRACT few more corrections

### ISSUE THREAD

**Issue by roshstar1999** [aradhana-arts/final_year_project_latex#6]
1 .line 3 2nd para of ABSTRACT

"movements of a listener " 
replace by:
"movements of the listener "

2.line 6 2nd para
"geometrical formula" <===> geometrical formulae

3.last line of 2nd para
"and the same processors used by sound systems" <==>" and the same processors can be used by sound systems"

if u ok with changing " I"  to "person A" then first para can be edited this way:
"
 Let us say a person A configured the orientation and
volume levels of the sound system to get perfect surround sound at some position where he is usually seated.
However, if he wants to change his sitting position,
or even arrangement to some other part of the room
which could be far right or left, or maybe forward or
backward from the last seating arrangement, in this
case, to get perfect surround sound, person A needs to reconfigure the speakers again( eg. speaker orientation and
volume levels) as per the new seat position, either
with the assistance of a  technician or on his own, which are mostly
manual adjustments.
"

**Comment by aradhana-arts** [comment]
All issues resolved except third suggestion, here we are trying to mention we can use the same algorithm and hardware on the existing processors which is currently used my audio systems. And not the processors which we a re using.
