### ISSUE TITLE
LITERATURE SURVEY and CONCLUSIONS corrections

### ISSUE THREAD

**Issue by roshstar1999** [aradhana-arts/final_year_project_latex#7]
in LITERATURE SURVEY 
1.C section first line

"In this paper given method the use of "<==>" In this paper, the given method makes the use of "

in conclusions,
2.
complexity of Hardware<==> hardware    (I'm not sure if its needed , but still mentioning)

if making this above change ,then change Algorithm<==> algorithm

**Comment by aradhana-arts** [comment]
Issues resolved
