### ISSUE TITLE
CHAPTER 3:in methodology

### ISSUE THREAD

**Issue by roshstar1999** [aradhana-arts/final_year_project_latex#8]
the page no. mentioned her are the page no. at the bottom of the page on the pdf

1.Page8 5th line
" system. Which consists of"<==> "system, which consists of the following:"

2.Page 8 Specifications 3rd point 
" linux compatible"<==>"Linux compatible"

3.PAge 9 Servo motors 1st point:
"90 in" <==>"90 degrees in"

page 10 3.4.5:
" and dynamically controlled sound using Audio Processor"<==>
" and the sound is dynamically controlled  using Audio Processor"

**Comment by aradhana-arts** [comment]
Issues resolved
