### ISSUE TITLE
chapter 4 4.1 DEPTH ESTIMATION UNIT

### ISSUE THREAD

**Issue by roshstar1999** [aradhana-arts/final_year_project_latex#9]
1.below the camera image:
"
Placed at some known distance x from each other
(24 cm). And implements computer vision (opencv)
and geometrical equations to measure the depth, deviation and hieght of a object from a reference point.
Where the reference point is the center of the stereo
vision system.
"
to =>

"The cameras are placed at some known distance x from each other
(24 cm) and  computer vision (opencv)
and geometrical equations have been implemented to measure the depth, deviation and height of an object from a reference point,
where the reference point is the center of the stereo
vision system.
"

#the corrections done above are spelling corrections and the full stops removed ,and a few letter non-capitalized

**Comment by aradhana-arts** [comment]
Resolved
